version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: docker/backend.Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  #   depends_on:
  #     - postgres
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/frontend.Dockerfile
  #     args:
  #       - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
  #   depends_on:
  #     - postgres
  # ws:
  #   build:
  #     context: .
  #     dockerfile: docker/ws.Dockerfile
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
